name = "LBFGSB"
uuid = "5be7bae1-8223-5378-bac3-9e7378a2f6e6"
authors = ["Yupei Qi <qiyupei@gmail.com>"]
version = "0.4.0"

[deps]
L_BFGS_B_jll = "81d17ec3-03a1-5e46-b53e-bddc35a13473"

[compat]
julia = "1.3.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
